# Generated by Django 5.2.5 on 2025-08-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel_bio_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
    ]
