# Generated by Django 5.2.5 on 2025-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel_first_name_profilemodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
