# Generated by Django 5.2.5 on 2025-08-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Study', 'Study'), ('Family', 'Family'), ('Health', 'Health'), ('Finance', 'Finance'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Hobbies', 'Hobbies'), ('Sports', 'Sports'), ('Others', 'Others')], default='Others', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
