# Generated by Django 5.2.1 on 2025-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_dead_line_taskmodel_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, default='This task does not have a description yet.', max_length=1000),
        ),
    ]
