# Generated by Django 5.2.5 on 2025-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(blank=True, default='earth', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, default='01*******', max_length=100, null=True),
        ),
    ]
